name: "@42js/pr-checker"
description: "@42js/piscine PR check github action 입니다."
author: "JaeSeoKim <jaeskim@student.42seoul.kr>"

inputs:
  repo-token:
    description: "The GITHUB_TOKEN secret"
    required: true
  configuration-path:
    description: "The path for the pr-checker configurations"
    default: ".github/labeler.yml"
    required: false
  currect-label:
    description: "정상적인 제출일 때 붙여줄 라벨"
    required: true
  wrong-label:
    description: "비 정상적인 제출일 때 붙여줄 라벨"
    required: true

runs:
  using: "node12"
  main: "dist/index.js"
